### PR TITLE
translate the example_acm R code to Python code

### PR DESCRIPTION
**Pull request by ruijis**
The python code is provided in the Jupyter Notebook.
The Notebook can be run online through a Binder page.
Required packages are specified in the YAML file.

### CODE REVIEW

**Comment by tom-parkinson** [comment]
Thanks @ruijis for the first pass on this. I've assigned @FedericoTartarini as the reviewer as I'm not proficient enough in Python to suggest best practices.

**Comment by FedericoTartarini** [comment]
Hi @ruijis thank you for putting this together. 

1. There are some warnings when I try to run the code and some errors. Could you please try to fix them? 
2. I am also not 100% sure of what it would be the benefit of having this code here. Its scope is very limited. It would be better to have a piece of code which describes the database more broadly.
3. I am not a huge fan of Jupiter notebooks, if anything I would simply recommend putting a simple Python file and the reqirements.txt file so other people can clone this repository locally and run the code on their machines. Jupiter notebook files have a lot of unnecessary text in them and while it is nice that people can run them in their browser then to edit the file is a bit of a pain.

Despite the above, if you think there is a benefit of having this file here, please simply fix point one and I can approve the pull request.

**Comment by tom-parkinson** [comment]
Thanks @FedericoTartarini. The benefit of sharing the Python code is to demonstrate to a new user how they could start their data analysis. It is an example of basic things like combining fields from the metadata table with the measurements table. By offering Python and R code, we would cover almost all users.

I'm also okay with more broad examples but that is going to take a bigger time investment. This is nicely scoped, so I'm inclined to support the suggestion fix point 1 and then share with community. Thanks!

**Comment by tom-parkinson** [comment]
Eventually I'd love to encourage people who use DBII to share their code when they publish. This could become a repository, although I'm not sure how we would do QA. But it would be nice to have a single resource that people can use to reproduce analyses.

**Comment by FedericoTartarini** [comment]
I fully agree people should share their code. But I am unsure whether we should encourage everyone to share it here. We could perhaps have a generic code here that we keep up to date and contains nice and interesting visualizations, for example, your code about the adaptive model. We could add a readme that links to all the papers, and their relative public code, that have used our dataset. However, maintaining that is hard and time-consuming.

**Comment by tom-parkinson** [comment]
Yeah you're right, the idea of generic code is a more suitable option. I'll think of ways to formalise it.

**Comment by ruijis** [comment]
Thanks for all the great comments!
- to point 1, I will find time to fix the warnings. I might keep the PR for some time, as it can generate a nice graph
- to point 2, as part of my thesis, I would like to create another Notebook for general data visualization of the database, e.g. histogram distribution of ages, world map of countries that contribute data, etc.
- I think the Jupyter Notebook is better than Python code because the objective is for data analysis and visualization.
- As a student of Fernando Perez, I have fallen in love with Jupyter Notebook. With the help of Binder, it becomes an awesome Docker container-based infrastructure for reproducible science. I can't imagine how people struggle to keep their environment the same as mine.
- to point 3, I agree that putting it all into a python file would be better in the case of calculating the adaptive thermal comfort model.

Q: Is there any existing python code for the adaptive model? e.g., in CBE thermal comfort tool?

Todo list
- [ ] adaptive_thermal_comfort_model.py
- [ ] db2_visualization.ipynb
- [ ] fix warnings in the notebook

**Comment by FedericoTartarini** [comment]
What do you mean by: Q: Is there any existing python code for the adaptive model? e.g., in CBE thermal comfort tool?

There are functions to calculate the adaptive model in pythermalcomfort. 

Sure, you can keep Jupiter notebooks, it is not a problem at all, mine was just a suggestion. I do not like them at all unless they are used for teaching, but this does not mean we should not have them here. More code and more approaches are better. I would love to see how you use them, there must be something that I do not understand about them since for me they are just messy and inefficient. I am looking forward to see the final version of the notebook and maybe you will convince me of the opposite 🙂

**Comment by ruijis** [comment]
@FedericoTartarini, I will be sure to take your suggestion for this PR.

What does the adaptive model look like in pythermalcomfort? Is it just a linear model with fixed coefficients, or it includes some functions like calculating the neutral temperature of a building?

**Comment by FedericoTartarini** [comment]
This is the [adaptive function](https://pythermalcomfort.readthedocs.io/en/latest/reference/pythermalcomfort.html#adaptive-ashrae) in pythermalcomfort which is the same as the one in the standard. Yes, it is a linear model with fixed coefficients. No it does not includes function to calculate the neutral temperature in a building. I am not sure how you would do that.

**Pull request closed without merging**
